# Copyright 2017, IBM.
#
# This source code is licensed under the Apache License, Version 2.0 found in
# the LICENSE.txt file in the root directory of this source tree.

notifications:
    on_success: change
    on_failure: always

cache: pip
sudo: false
os: linux
dist: trusty

language: python
python:
    - "3.6"

# Install Qiskit Terra from master branch
env: CMAKE_FLAGS="-D CMAKE_CXX_COMPILER=g++-5 -D ENABLE_TARGETS_QA=False -D WHEEL_TAG=-pmanylinux1_x86_64 -D STATIC_LINKING=True"
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - liblapack-dev
        - libblas-dev
        - g++-5
before_install:
    # download Qiskit Terra master and unzip it
    - wget https://codeload.github.com/Qiskit/qiskit-terra/zip/master -O /tmp/qiskit-terra-master.zip
    - unzip /tmp/qiskit-terra-master.zip -d /tmp/
    # Install Qiskit Terra dependencies.
    - pip install -U -r /tmp/qiskit-terra-master/requirements.txt
    - pip install -U -r /tmp/qiskit-terra-master/requirements-dev.txt
    # Create the basic cmake structure, setting out/ as the default dir.
    - cd /tmp/qiskit-terra-master
    - mkdir out && cd out && cmake $CMAKE_FLAGS ..
    # Compile the executables
    - make
    # Install local Qiskit Terra
    - pip install -e /tmp/qiskit-terra-master
    # back to current repo directory
    - cd $TRAVIS_BUILD_DIR

# Test 
install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt
script:
    - python -m unittest discover -v test